#!/usr/bin/env node
/*
 * pibot - Binary executable to create a bot
 */

/*
 * Requiring modules
 */
var winston = require('winston').cli()
  , path = require('path')
  , fs = require('fs');

/*
 * Build variables
 */
var botname = process.argv[2];
var target = path.join(path.resolve(process.argv[3]), botname);

/*
 * Create directory
 */
if (!path.existsSync(target)) {
  try {
    fs.mkdirSync(target, 0755);
  } catch (err) {
    winston.error(err);
    process.exit(1);
  }
  winston.info(('Created directory ' + target).cyan);
}

/*
 * Make schemas directory
 */
var schemas = path.join(target, 'schemas');
if (!path.existsSync(schemas)) {
  fs.mkdirSync(schemas, 0755);
  fs.writeFileSync(path.join(schemas, '.gitkeep'), '');
  winston.info('Created schemas directory'.yellow);
}

/*
 * Make scripts directory
 */
var scripts = path.join(target, 'scripts');
if (!path.existsSync(scripts)) {
  fs.mkdirSync(scripts, 0755);
  fs.writeFileSync(path.join(scripts, '.gitkeep'), '');
  winston.info('Created scripts directory'.magenta);
}

/*
 * Copy files
 */
['.gitignore', 'index.js', 'package.json', 'config.json'].forEach(function (e,i,a) {
  fs.readFile(path.resolve(path.join(__dirname, 'scaffold', e)), 'utf8', function (err, data) {
    if (err) throw err;
    fs.writeFile(path.join(target, e), data.replace('botname', botname), 'utf8', function (err) {
       if (err) throw err;
       winston.info(('Copied file "' + e + '"').cyan);
    });
  });
});
