#!/usr/bin/env node
/*
 * pibot - Binary executable to create a bot
 */

/*
 * Requiring modules
 */
var winston = require('winston')
    , path = require('path')
    , fs = require('fs');

/*
 * Build variables
 */
var target = path.resolve(process.argv[3]);
var botname = process.argv[2];

/*
 * Create directory
 */
if (!path.existsSync(path.join(target, botname))) {
  try {
    fs.mkdirSync(path.join(target, botname), 0755);
  } catch (err) {
    winston.error(err);
    process.exit(1);
  }
  winston.info('Created directory ' + path.join(target, botname));
}

/*
 * Copy files
 */
