/*
 * botname - generated by pibot
 */
var pibot = require('pibot')
  , fs = require('fs')
  , path = require('path');

/*
 * Calculate paths
 */
var paths = [__dirname];
var deps = fs.readdirSync(path.join(__dirname, 'node_modules'));

deps.forEach(function (e,i,a) {
  if (e.match(/pibot-[^-].*/)) {
    paths.push(path.join(__dirname, 'node_modules', e));
  }
});

/*
 * Initialize bot
 */
pibot.init('./config.json', paths);
